-- FitGym class catalog reset
-- Replaces the current classes_admin catalog with a recommendation-ready set of classes.

START TRANSACTION;

ALTER TABLE classes_admin
  ADD COLUMN IF NOT EXISTS goal_endurance TINYINT(1) NOT NULL DEFAULT 0 AFTER goal_muscle_gain,
  ADD COLUMN IF NOT EXISTS goal_mobility TINYINT(1) NOT NULL DEFAULT 0 AFTER goal_endurance,
  ADD COLUMN IF NOT EXISTS goal_flexibility TINYINT(1) NOT NULL DEFAULT 0 AFTER goal_mobility,
  ADD COLUMN IF NOT EXISTS goal_stress_relief TINYINT(1) NOT NULL DEFAULT 0 AFTER goal_flexibility;

DELETE FROM classes_admin;
ALTER TABLE classes_admin AUTO_INCREMENT = 1;

INSERT INTO classes_admin (
    name,
    slug,
    category,
    description,
    trainer_account_id,
    weekly_schedule,
    max_participants,
    active,
    intensity_level,
    fitness_level,
    goal_fat_loss,
    goal_maintenance,
    goal_muscle_gain,
    calories_burn_min,
    calories_burn_max,
    tdee_min,
    tdee_max,
    duration_minutes,
    recommended_frequency_per_week,
    low_impact,
    joint_friendly,
    requires_equipment,
    is_active
) VALUES
(
    'Yoga Foundations',
    'yoga-foundations',
    'yoga',
    'Beginner-friendly yoga focused on posture, breathing control, mobility, and steady low-impact conditioning.',
    305,
    'Mon, Wed, Fri 7:00-8:00 AM',
    16,
    1,
    'low',
    'beginner',
    1,
    1,
    0,
    120,
    190,
    NULL,
    2800,
    50,
    3,
    1,
    1,
    0,
    1
),
(
    'Chair Yoga Mobility',
    'chair-yoga',
    'yoga',
    'Gentle seated and supported yoga for recovery, mobility, and consistent movement with joint-friendly pacing.',
    305,
    'Tue, Thu 9:00-10:00 AM',
    14,
    1,
    'low',
    'beginner',
    1,
    1,
    0,
    90,
    150,
    NULL,
    2400,
    40,
    2,
    1,
    1,
    0,
    1
),
(
    'Beginner Pilates',
    'beginner-pilates',
    'pilates',
    'Core-focused pilates sessions that improve posture, control, and moderate calorie burn for newer members.',
    305,
    'Mon, Wed, Fri 8:00-9:00 AM',
    14,
    1,
    'low',
    'beginner',
    1,
    1,
    0,
    140,
    220,
    NULL,
    NULL,
    45,
    3,
    1,
    1,
    0,
    1
),
(
    'Pilates Core Flow',
    'pilates-core',
    'pilates',
    'Progressive pilates flow with stronger core sequences, balance work, and controlled medium-intensity movement.',
    305,
    'Tue, Thu, Sat 7:00-8:00 AM',
    14,
    1,
    'medium',
    'beginner',
    1,
    1,
    0,
    180,
    280,
    NULL,
    NULL,
    50,
    3,
    1,
    1,
    0,
    1
),
(
    'Recovery Mobility',
    'recovery-mobility',
    'recovery',
    'Low-stress mobility and flexibility work designed for recovery days, posture support, and light maintenance training.',
    305,
    'Tue, Thu 6:00-7:00 PM',
    18,
    1,
    'low',
    'beginner',
    0,
    1,
    0,
    70,
    130,
    NULL,
    2600,
    35,
    2,
    1,
    1,
    0,
    1
),
(
    'Aqua Cardio Conditioning',
    'aqua-cardio',
    'cardio',
    'Pool-based cardio conditioning that raises heart rate while staying low impact and easy on the joints.',
    1367,
    'Mon, Wed, Fri 12:00-1:00 PM',
    12,
    1,
    'medium',
    'beginner',
    1,
    1,
    0,
    220,
    320,
    NULL,
    3200,
    45,
    3,
    1,
    1,
    1,
    1
),
(
    'Zumba',
    'zumba',
    'dance',
    'Dance-cardio intervals with easy choreography, upbeat music, and reliable calorie burn for general fitness.',
    1367,
    'Mon, Wed, Fri 6:00-7:00 AM',
    22,
    1,
    'medium',
    'beginner',
    1,
    1,
    0,
    280,
    400,
    NULL,
    NULL,
    50,
    3,
    0,
    0,
    0,
    1
),
(
    'Dance Cardio',
    'dance',
    'dance',
    'Fast-moving cardio dance class for coordination, stamina, and consistent moderate calorie expenditure.',
    1367,
    'Tue, Thu, Sat 5:00-6:00 PM',
    20,
    1,
    'medium',
    'beginner',
    1,
    1,
    0,
    240,
    360,
    NULL,
    NULL,
    45,
    3,
    0,
    0,
    0,
    1
),
(
    'Cardio Circuit',
    'cardio-circuit',
    'cardio',
    'Station-based cardio intervals with bodyweight drills, short bursts, and repeatable moderate-to-high output.',
    1367,
    'Mon, Tue, Thu, Sat 5:00-6:00 PM',
    18,
    1,
    'medium',
    'intermediate',
    1,
    1,
    0,
    300,
    420,
    NULL,
    NULL,
    45,
    4,
    0,
    0,
    0,
    1
),
(
    'Boxing Cardio',
    'boxing-cardio',
    'cardio',
    'Boxing-inspired conditioning that builds stamina, footwork, and high calorie burn through pad and bag rounds.',
    1367,
    'Mon, Wed, Fri 7:00-8:00 PM',
    16,
    1,
    'high',
    'intermediate',
    1,
    1,
    0,
    380,
    520,
    1900,
    NULL,
    45,
    3,
    0,
    0,
    1,
    1
),
(
    'HIIT Burn',
    'hiit-burn',
    'hiit',
    'Short, aggressive HIIT work blocks for members targeting fat loss, conditioning, and higher session burn.',
    1022,
    'Mon, Tue, Thu, Fri 6:00-7:00 PM',
    16,
    1,
    'high',
    'intermediate',
    1,
    0,
    0,
    420,
    620,
    2000,
    NULL,
    35,
    4,
    0,
    0,
    0,
    1
),
(
    'Cycling Intervals',
    'cycling-intervals',
    'cardio',
    'Bike-based interval training with progressive resistance for strong cardio output and maintenance conditioning.',
    1367,
    'Tue, Thu, Sat, Sun 6:00-7:00 AM',
    14,
    1,
    'high',
    'intermediate',
    1,
    1,
    0,
    400,
    560,
    2000,
    NULL,
    45,
    4,
    0,
    0,
    1,
    1
),
(
    'Strength Foundations',
    'strength-foundations',
    'strength',
    'Foundational resistance training class centered on safe lifting patterns, control, and progressive strength gains.',
    1022,
    'Mon, Wed, Fri 4:00-5:00 PM',
    12,
    1,
    'medium',
    'beginner',
    0,
    1,
    1,
    180,
    280,
    NULL,
    NULL,
    55,
    3,
    0,
    0,
    1,
    1
),
(
    'Resistance Band Strength',
    'band-strength',
    'strength',
    'Joint-friendly resistance band training for early-stage strength work, muscle activation, and controlled progression.',
    1022,
    'Tue, Thu, Sat 12:00-1:00 PM',
    12,
    1,
    'low',
    'beginner',
    0,
    1,
    1,
    150,
    230,
    NULL,
    2400,
    45,
    3,
    1,
    1,
    1,
    1
),
(
    'Strength Build',
    'strength-build',
    'strength',
    'Compound strength sessions for members ready for heavier resistance work and muscle-building progression.',
    1022,
    'Mon, Tue, Thu, Fri 7:00-8:00 AM',
    12,
    1,
    'high',
    'intermediate',
    0,
    1,
    1,
    240,
    360,
    1800,
    NULL,
    60,
    4,
    0,
    0,
    1,
    1
),
(
    'Kettlebell Conditioning',
    'kettlebell-conditioning',
    'strength',
    'Strength-endurance training using kettlebells for posterior-chain work, conditioning, and controlled power output.',
    1022,
    'Mon, Wed, Fri 5:00-6:00 PM',
    14,
    1,
    'medium',
    'intermediate',
    1,
    1,
    1,
    260,
    380,
    1800,
    NULL,
    45,
    3,
    0,
    0,
    1,
    1
),
(
    'Power Lift Performance',
    'power-lift-basics',
    'strength',
    'Advanced barbell training built around heavy compound lifts, technical progression, and higher-volume strength blocks.',
    1022,
    'Tue, Thu, Sat, Sun 8:00-9:00 AM',
    10,
    1,
    'high',
    'advanced',
    0,
    1,
    1,
    260,
    380,
    2100,
    NULL,
    70,
    4,
    0,
    0,
    1,
    1
),
(
    'Athletic Bootcamp',
    'athletic-bootcamp',
    'mixed',
    'Full-body bootcamp with sprint intervals, bodyweight circuits, and advanced conditioning for high-output members.',
    1367,
    'Mon, Wed, Fri, Sat 6:00-7:00 AM',
    18,
    1,
    'high',
    'advanced',
    1,
    1,
    0,
    450,
    650,
    2200,
    NULL,
    50,
    4,
    0,
    0,
    0,
    1
);

UPDATE bookings
SET class_slug = 'zumba',
    class_name = 'Zumba',
    trainer_name = 'Hari Tamang'
WHERE LOWER(class_slug) = 'zumba';

UPDATE bookings
SET class_slug = 'dance',
    class_name = 'Dance Cardio',
    trainer_name = 'Hari Tamang'
WHERE LOWER(class_slug) = 'dance';

UPDATE bookings
SET class_slug = 'beginner-pilates',
    class_name = 'Beginner Pilates',
    trainer_name = 'Trainer Dai'
WHERE LOWER(class_slug) = 'beginner-pilates';

UPDATE classes_admin
SET goal_endurance = 1
WHERE slug IN (
    'aqua-cardio',
    'zumba',
    'dance',
    'cardio-circuit',
    'boxing-cardio',
    'hiit-burn',
    'cycling-intervals',
    'athletic-bootcamp',
    'kettlebell-conditioning'
);

UPDATE classes_admin
SET
    goal_mobility = 1,
    goal_flexibility = 1
WHERE slug IN (
    'yoga-foundations',
    'chair-yoga',
    'beginner-pilates',
    'pilates-core',
    'recovery-mobility'
);

UPDATE classes_admin
SET goal_stress_relief = 1
WHERE slug IN (
    'yoga-foundations',
    'chair-yoga',
    'recovery-mobility'
);

COMMIT;
